### ISSUE TITLE
change pthread_mutex_t to pthread_spinlock_t

### ISSUE THREAD

**Issue by cmpxchg16** [pramalhe/ConcurrencyFreaks#1]
Hi!

All the lock implementation based on some spin (sched_yield), but you compare with pthread lock that could block, to get better comparison change the pthread from mutex to spin.
Note that when I tested with pthread_spinlock_t it give the best ops/s (So on when I changed  the spin implementation to sched_yield in between).

J

**Comment by pramalhe** [comment]
Thanks for the suggestion. I think most users prefer pthread_mutex_t so we're going to leave it as it is, particularly because of the fairness (spinlock is fast because it's highly unfair and one thread is always hot in cache).
