### ISSUE TITLE
tests missing in benchmarking 

### ISSUE THREAD

**Issue by shekhar108** [pramalhe/ConcurrencyFreaks#3]
In benchmarking, com/concurrencyfreaks/tests is missing which is used by BenchmarkListRelaxedvsVolatile.java

**Comment by pramalhe** [comment]
This was only needed to get the output in csv format, but good point. I've added the missing class to the repo.
Keep in mind that the two CLLElectedUnlink classes do not conform to the Java memory model, and as such, they're not "correct" in the JMM sense  ;)
