### ISSUE TITLE
[java] miss some classes , can't compile

### ISSUE THREAD

**Issue by CatCodeMe** [pramalhe/ConcurrencyFreaks#5]
- DoubleInstanceLockGuard.class ![image](https://user-images.githubusercontent.com/11496772/56419418-c76a6580-62cc-11e9-96c5-eac8184ad196.png)
- LongAdderExtRWLock.class 
![image](https://user-images.githubusercontent.com/11496772/56419481-f1238c80-62cc-11e9-8f9e-b81f0e8e2023.png)

**Comment by pramalhe** [comment]
Thanks for spotting this!
I've uploaded the necessary files. Hopefully haven't introduced more missing dependencies.
Thanks,
Pedro
