### ISSUE TITLE
No LICENSE.txt file?

### ISSUE THREAD

**Issue by Valloric** [pramalhe/ConcurrencyFreaks#6]
You don't have a license file in your repo, making your code impossible to reuse in a commercial or open-source context.

Could you please add a license? May I recommend you use Apache 2.0 because it's both business and open-source friendly (covers patents, copyright, contributions etc).

[Here's what GitHub's own Choose-A-License site has to say about the Apache 2.0 license](https://choosealicense.com/licenses/apache-2.0/)

But really, just pick _a_ license, even if it is to say "we do not provide a copyright license at all, you cannot re-use this code" to reduce confusion. (Although I'd greatly prefer it if you used a liberal open-source license.)

Disclaimer: I am not a lawyer and this is not legal advice.

**Comment by Valloric** [comment]
I just noticed that you have license terms in your source files; great! Having a LICENSE.txt file would still help in reducing confusion (as can be seen with this issue report).

**Comment by pramalhe** [comment]
Yep, most files have a copyright notice in them, but good point: I've added
a LICENSE.txt to the repo (MIT license)
Thanks for the heads-up Val!

**Comment by Valloric** [comment]
Thanks!

I just spot-checked various files in the CPP and java folders and all the files I saw used BSD 3-Clause license, not the MIT license. 

Not sure did you intend to use the MIT license at the repo level then; if you did, it might be a good idea to mention at the top of the file that some files use a different license, otherwise confusion will probably be much worse.
